### ISSUE TITLE
docker push fails if image is not changed

### ISSUE THREAD

**Issue by islamahmad** [mum-courses/K8s-demo#4]
docker push fails while creating deployment if the image created is the same as the one on hub.docker.com

**Comment by mum-courses** [comment]
Unable to reproduce the scenario when using latest as tag.

It depends on your repo settings, by default you should be able to override existing image tag.

Check [override a tag](https://docs.docker.com/ee/dtr/user/manage-images/prevent-tags-from-being-overwritten/)

FYI:
Latest is not what it seems to be -> [The misunderstood tag](https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375)
